# Generated by Django 4.0.2 on 2022-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointement', '0004_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reschedule',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
