# Generated by Django 4.0.2 on 2022-02-23 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointement', '0005_alter_reschedule_accepted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
    ]
